POST http://localhost:8080/events
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZXhhbXBsZS5jb20iLCJleHAiOjE3ODk0NTMxMjYsInVzZXJJZCI6MX0.Nre5VZ37dAOX5rHu3lE3vkfYjUOrCkJgdfwOTKkjIyI

{
    "name": "Test event ",
    "description": "Another test event",
    "location": "A test location",
    "dateTime": "2025-01-01T15:30:00.000Z"
}